// Reviewed ver2 changes. Generated by scripts/import-ver2-updates.py.
export const brochureUpdates = [
  {
    "id": "mcipcb13a",
    "name": "MCIPCB13A",
    "series": "B",
    "tagline": "Configurable Intel Core industrial PC with dual LAN and dual COM",
    "description": "MCIPCB13A offers Intel Core i3/i5/i7 processor options across the 4th, 6th, 7th, 8th, 10th, 12th and 13th generations, with DDR3L, DDR4 or DDR5 memory depending on the platform. The 12th/13th Gen configuration supports up to 64GB DDR5. Dual Gigabit Ethernet, two DB9 COM ports, eight USB ports and 12–19V input fit a 193.9 x 127 x 57.2 mm enclosure.",
    "highlights": [
      "Intel Core options",
      "2 x Gigabit LAN",
      "2 x DB9 COM",
      "12–19V DC input"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCIPCB13A"
      },
      {
        "label": "CPU",
        "value": "Optional Intel 4th/6th/7th/8th/10th/12th/13th Gen Core i3/i5/i7 CPU"
      },
      {
        "label": "Display",
        "value": "1 x HDMI, 1 x VGA (or HDMI)"
      },
      {
        "label": "Memory",
        "value": "4th Gen: 1 x DDR3L SODIMM, maximum support 8GB; 6th/7th/8th Gen: 1 x DDR4 SODIMM, maximum support 16GB; 8th/10th Gen: 2 x DDR4 SODIMM, maximum support 32GB; 12th/13th Gen: 1 x DDR5 SODIMM, maximum support 64GB"
      },
      {
        "label": "USB",
        "value": "4 x USB 3.0, 4 x USB 2.0"
      },
      {
        "label": "Power",
        "value": "DC 12V-19V Power Input"
      },
      {
        "label": "Network",
        "value": "2 x GbE RJ45 x Realtek 8111H"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM"
      },
      {
        "label": "Storage",
        "value": "4th Gen: 1 x MSATA; 6th/7th/8th/10th/12th/13th Gen: 1 x M.2 2280 (Supports SATA and NVME); 1 x 2.5\" HDD/SSD"
      },
      {
        "label": "Expansion",
        "value": "1 x Mini-PCIe half/full card (with SIM slot, supports 3G/4G, Wi-Fi/Bluetooth); Supports Watchdog, Diskless boot"
      },
      {
        "label": "Dimensions",
        "value": "193.9 x 127 x 57.2 mm"
      },
      {
        "label": "OS",
        "value": "Windows 7/8/10, WES 7/10, LINUX"
      },
      {
        "label": "Environment - Operating",
        "value": "Working Temp: -20°C to +60°C; Storage Temp: -30°C to +70°C; Storage Humidity: 10%~90% @30, non-condensing"
      },
      {
        "label": "Front I/O - Ports",
        "value": "1 x Power Button; 4 x USB 3.0; 4 x USB 2.0; 2 x DB9 COM (COM1, COM2)"
      },
      {
        "label": "Rear I/O - Ports",
        "value": "1 x DC Power Input (12V-19V); 2 x GbE RJ45 LAN; 1 x HDMI; 1 x VGA; 1 x Earphone jack, 1 x Microphone; 2 x Antenna connectors (for Wi-Fi/3G/4G)"
      }
    ],
    "image": "/assets/products/industrial/ver2/mcipcb13a/main.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mcipcb13a/view-1.webp",
      "/assets/products/industrial/ver2/mcipcb13a/view-2.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mcipcb13a/view-1.webp",
        "title": "MCIPCB13A front panel"
      },
      {
        "image": "/assets/products/industrial/ver2/mcipcb13a/view-2.webp",
        "title": "MCIPCB13A rear panel"
      }
    ],
    "sourceBrochure": "工控机IPC/B系列/MCIPCB13A brochure.pdf",
    "sourceSha256": "363189e22ab6dd228f131176356621199904e7287d98c53414995132eff4d483",
    "operatingRange": "-20°C to 60°C"
  },
  {
    "id": "mcipcb13b",
    "name": "MCIPCB13B",
    "series": "B",
    "tagline": "Intel Core Ultra / Core 3 industrial PC with DDR5 and triple display",
    "description": "MCIPCB13B supports Intel Core Ultra Series 1/2 or Core 3 Series processors, up to 64GB DDR5, dual Gigabit LAN, two RS-232 ports, two HDMI outputs and DisplayPort. USB allocation and 2.5-inch storage availability depend on the selected processor platform.",
    "highlights": [
      "Core Ultra / Core 3",
      "Up to 64GB DDR5",
      "2 x HDMI + DisplayPort",
      "12–19V DC input"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCIPCB13B"
      },
      {
        "label": "CPU",
        "value": "Optional Intel Core Ultra Series 1/2 U5/U7 processors; Intel Core 3 Series 304/305/315/320/330/350/360 processors"
      },
      {
        "label": "Memory",
        "value": "1 x DDR5 SODIMM, maximum 64 GB"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "USB",
        "value": "Core Ultra Series 1/2: 4 x USB 3.0, 4 x USB 2.0; Core 3 Series: 2 x USB 3.0, 6 x USB 2.0"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 RS-232 ports"
      },
      {
        "label": "Display",
        "value": "2 x HDMI; 1 x DisplayPort"
      },
      {
        "label": "Ports",
        "value": "1 x headphone jack; 1 x microphone jack"
      },
      {
        "label": "Storage",
        "value": "1 x M.2 2280 NVMe SSD; 1 x 2.5-inch HDD/SSD (not supported on Core 3 Series)"
      },
      {
        "label": "Expansion",
        "value": "1 x M.2 2232 for Wi-Fi; 1 x M.2 3042 for 3G/4G, with onboard SIM slot; 2 x antenna connectors"
      },
      {
        "label": "Power",
        "value": "12-19 V DC input"
      },
      {
        "label": "OS",
        "value": "Windows 10; Windows 11; Linux"
      },
      {
        "label": "Material",
        "value": "Aluminium"
      },
      {
        "label": "Mounting",
        "value": "Desktop or wall mounting"
      },
      {
        "label": "Dimensions",
        "value": "193.9 x 127 x 57.2 mm"
      },
      {
        "label": "Weight",
        "value": "1 kg"
      },
      {
        "label": "Environment - Operating",
        "value": "Operating temperature: -20 C to +60 C; storage temperature: -30 C to +70 C; storage humidity: 10%~90% at 30 C, non-condensing"
      },
      {
        "label": "Other",
        "value": "Supports watchdog and diskless boot"
      }
    ],
    "image": "/assets/products/industrial/ver2/mcipcb13b/main.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mcipcb13b/view-1.webp",
      "/assets/products/industrial/ver2/mcipcb13b/view-2.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mcipcb13b/view-1.webp",
        "title": "MCIPCB13B front panel"
      },
      {
        "image": "/assets/products/industrial/ver2/mcipcb13b/view-2.webp",
        "title": "MCIPCB13B rear panel"
      }
    ],
    "sourceBrochure": "工控机IPC/B系列/MCIPCB13B brochure.pdf",
    "sourceSha256": "4c8b5218453dd43168abd6390967541e008a59684668bc0b0dec8596da87f9e0",
    "operatingRange": "-20°C to 60°C"
  },
  {
    "id": "mcipce1",
    "name": "MCIPCE1",
    "series": "E",
    "tagline": "Intel Core i7-1360P industrial PC with four LAN ports and 9–36V input",
    "description": "MCIPCE1 combines an Intel Core i7-1360P, up to 32GB DDR4, two Gigabit and two 2.5GbE ports, six serial ports, and 14 GPIO signals. Four serial ports support RS-485/RS-422. A 9–36V Phoenix terminal input, multiple storage interfaces, and desktop or wall mounting support custom industrial deployments.",
    "highlights": [
      "Intel Core i7-1360P",
      "2 x GbE + 2 x 2.5GbE",
      "6 x COM + 14 GPIO",
      "9–36V DC input"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCIPCE1"
      },
      {
        "label": "CPU",
        "value": "Intel® Core™ i7-1360P Processor"
      },
      {
        "label": "Memory",
        "value": "2 x DDR4 SO-DIMM, up to 32 GB"
      },
      {
        "label": "Display",
        "value": "1 x HDMI; 1 x VGA"
      },
      {
        "label": "Network",
        "value": "2 x Intel GbE; 2 x Intel 2.5 GbE"
      },
      {
        "label": "USB",
        "value": "4 x USB 3.0; 6 x USB 2.0"
      },
      {
        "label": "Serial",
        "value": "6 x RS-232 COM; 4 ports support RS-485/RS-422"
      },
      {
        "label": "GPIO",
        "value": "14 x GPIO: 7 inputs and 7 outputs"
      },
      {
        "label": "Other I/O",
        "value": "1 x PS/2; 1 x headphone; 1 x microphone; 2 x antenna ports"
      },
      {
        "label": "Buttons",
        "value": "1 x Power; 1 x Reset; 1 x Clear CMOS; 1 x ATX/AT selector"
      },
      {
        "label": "Storage",
        "value": "1 x mSATA; 1 x M.2 NVMe 2280; 1 x HDD/SSD bay"
      },
      {
        "label": "Expansion",
        "value": "1 x half-size Mini PCIe; 1 x full-size Mini PCIe with SIM; Wi-Fi/Bluetooth/3G/4G support"
      },
      {
        "label": "Power",
        "value": "DC 9-36 V via 3-pin Phoenix terminal"
      },
      {
        "label": "Firmware",
        "value": "Watchdog; one-key recovery; PXE/diskless boot"
      },
      {
        "label": "OS",
        "value": "Windows 10; Windows Embedded Standard 7/10; Linux"
      },
      {
        "label": "Material",
        "value": "Aluminum"
      },
      {
        "label": "Installation",
        "value": "Desktop or wall mount"
      },
      {
        "label": "Dimensions",
        "value": "248 x 150 x 83 mm"
      },
      {
        "label": "Weight",
        "value": "1.3 kg"
      },
      {
        "label": "Environment - Operating",
        "value": "-20 to 60 C"
      },
      {
        "label": "Environment - Storage",
        "value": "-30 to 70 C; 10%-90% RH at 30 C, non-condensing"
      }
    ],
    "image": "/assets/products/industrial/ver2/mcipce1/main.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mcipce1/view-1.webp",
      "/assets/products/industrial/ver2/mcipce1/view-2.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mcipce1/view-1.webp",
        "title": "MCIPCE1 front panel"
      },
      {
        "image": "/assets/products/industrial/ver2/mcipce1/view-2.webp",
        "title": "MCIPCE1 rear panel"
      }
    ],
    "sourceBrochure": "工控机IPC/E系列/MCIPCE1 Brochure.pdf",
    "sourceSha256": "9de88443cbf0b1795d08159ac9a753ab206596a89d78840db5cc69394835efd0",
    "operatingRange": "-20°C to 60°C"
  },
  {
    "id": "mc15uh",
    "name": "MC15UH",
    "series": "DPC",
    "tagline": "Intel Core Ultra desktop PC with USB4, OCuLink and dual 2.5GbE",
    "description": "MC15UH combines Intel Core Ultra 7 255H or Core Ultra 9 285H, Intel Arc 140T graphics, up to 128GB DDR5, dual NVMe storage, USB4 and OCuLink. HDMI, DisplayPort and USB4 provide display connectivity in a 132 x 132 x 50.5 mm desktop enclosure.",
    "highlights": [
      "Core Ultra 7 / 9",
      "Up to 128GB DDR5",
      "Dual 2.5GbE",
      "USB4 + OCuLink"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MC15UH"
      },
      {
        "label": "CPU",
        "value": "Intel Core Ultra 7 255H / Core Ultra 9 285H"
      },
      {
        "label": "Chipset",
        "value": "Arrow Lake-H"
      },
      {
        "label": "Graphics",
        "value": "Intel Arc 140T GPU"
      },
      {
        "label": "Display",
        "value": "1 x HDMI (8k@60Hz/4K@120Hz); 1 x DP (8k@60Hz/4K@160Hz); 1 x USB4 (4K@120Hz)"
      },
      {
        "label": "Memory",
        "value": "2 x SO-DIMM DDR5 5600MHz Supports up to 128GB"
      },
      {
        "label": "USB",
        "value": "3 x USB3.0; 1 x USB2.0"
      },
      {
        "label": "Power",
        "value": "19V/6.32A 120W"
      },
      {
        "label": "Network",
        "value": "2 x Intel i226V 2.5G Ethernet LAN"
      },
      {
        "label": "Storage",
        "value": "2 x M.2 2280 NVME SSD hard drive slot"
      },
      {
        "label": "Wireless",
        "value": "WiFi-6E, Bluetooth 5.3"
      },
      {
        "label": "Dimensions",
        "value": "132 x 132 x 50.5 mm"
      },
      {
        "label": "BIOS",
        "value": "AMI BIOS (Legacy or UEFI)"
      },
      {
        "label": "TDP",
        "value": "Depends on CPU"
      },
      {
        "label": "OS",
        "value": "Windows10/Windows11"
      },
      {
        "label": "Environment - Operating",
        "value": "0~50 C; 5%~90% Relative humidity; (no condensation)"
      },
      {
        "label": "Front I/O - Ports",
        "value": "1 x power button; 1 x RST reset hole; 2 x USB 3.0; 1 x 3.5mm Combined audio interface; 1 x USB4 40Gbps; 1 x OCulink Connect to graphics card expansion dock"
      },
      {
        "label": "Rear I/O - Ports",
        "value": "1 x DC IN 19V/6.32A; 2 x Intel i226V 2.5G Ethernet LAN; 1 x HDMI 2.1; 1 x DP 2.1"
      }
    ],
    "image": "/assets/products/commercial/ver2/mc15uh/main.webp",
    "galleryImages": [
      "/assets/products/commercial/ver2/mc15uh/view-1.webp",
      "/assets/products/commercial/ver2/mc15uh/view-2.webp",
      "/assets/products/commercial/ver2/mc15uh/view-3.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/commercial/ver2/mc15uh/view-1.webp",
        "title": "MC15UH front panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mc15uh/view-2.webp",
        "title": "MC15UH rear panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mc15uh/view-3.webp",
        "title": "MC15UH enclosure view"
      }
    ],
    "sourceBrochure": "桌面端DPC/MC15UH brochure.pdf",
    "sourceSha256": "7b28f881703d2e8fd4f1be76fbbf66771f7f9dfe4b8d953656d5c98ca3a43b99",
    "operatingRange": "0°C to 50°C"
  },
  {
    "id": "mcar9",
    "name": "MCAR9",
    "series": "DPC",
    "tagline": "AMD Ryzen AI 300 desktop PC with USB4 and OCuLink",
    "description": "MCAR9 provides AMD Ryzen AI 7 PRO 360, Ryzen AI 9 365 or Ryzen AI 9 HX 370 processor options, Radeon 880M/890M graphics, up to 128GB DDR5, dual 2.5GbE and dual NVMe storage. USB4 and OCuLink support high-speed peripherals and compatible external graphics docks.",
    "highlights": [
      "Ryzen AI 300",
      "Up to 128GB DDR5",
      "Dual 2.5GbE",
      "USB4 + OCuLink"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCAR9"
      },
      {
        "label": "CPU",
        "value": "AMD Ryzen AI 7 PRO 360 / Ryzen AI 9 365 / Ryzen AI 9 HX 370"
      },
      {
        "label": "Chipset",
        "value": "Ryzen AI 300"
      },
      {
        "label": "Graphics",
        "value": "AMD Radeon 880M/AMD Radeon 890M"
      },
      {
        "label": "Display",
        "value": "1 x HDMI (8k@60Hz/4K@120Hz); 1 x DP (8k@60Hz/4K@160Hz); 1 x USB4 (4K@120Hz)"
      },
      {
        "label": "Memory",
        "value": "2 x DDR5 SO-DIMM Memory slot, Up to 128GB 5600MHz"
      },
      {
        "label": "USB",
        "value": "3 x USB3.0; 1 x USB2.0"
      },
      {
        "label": "Power",
        "value": "19V/6.32A 120W"
      },
      {
        "label": "Network",
        "value": "2 x Intel i226V 2.5G Ethernet LAN"
      },
      {
        "label": "Storage",
        "value": "2 x M.2 2280 NVME SSD hard drive slot"
      },
      {
        "label": "Wireless",
        "value": "WiFi-6E, Bluetooth 5.3"
      },
      {
        "label": "Dimensions",
        "value": "132 x 132 x 50.5 mm"
      },
      {
        "label": "BIOS",
        "value": "AMI BIOS (Legacy or UEFI)"
      },
      {
        "label": "TDP",
        "value": "Depends on CPU"
      },
      {
        "label": "OS",
        "value": "Windows10/Windows11"
      },
      {
        "label": "Environment - Operating",
        "value": "0~50 C; 5%~90% Relative humidity; (no condensation)"
      },
      {
        "label": "Front I/O - Ports",
        "value": "1 x power button; 1 x RST reset hole; 2 x USB 3.0; 1 x 3.5mm Combined audio interface; 1 x USB4 40Gbps; 1 x OCulink Connect to graphics card expansion dock"
      },
      {
        "label": "Rear I/O - Ports",
        "value": "1 x DC IN 19V/6.32A; 2 x Intel i226V 2.5G Ethernet LAN; 1 x HDMI 2.1; 1 x DP 2.1; 1 x USB3.0; 1 x USB2.0"
      }
    ],
    "image": "/assets/products/commercial/ver2/mcar9/main.webp",
    "galleryImages": [
      "/assets/products/commercial/ver2/mcar9/view-1.webp",
      "/assets/products/commercial/ver2/mcar9/view-2.webp",
      "/assets/products/commercial/ver2/mcar9/view-3.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/commercial/ver2/mcar9/view-1.webp",
        "title": "MCAR9 front panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mcar9/view-2.webp",
        "title": "MCAR9 rear panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mcar9/view-3.webp",
        "title": "MCAR9 enclosure view"
      }
    ],
    "sourceBrochure": "桌面端DPC/MCAR9 brochure.pdf",
    "sourceSha256": "aff01a550701710ef41bbe50e90939b8fd3817ad8d83e93be546a2c5623f29f3",
    "operatingRange": "0°C to 50°C"
  },
  {
    "id": "mcn7a",
    "name": "MCN7A",
    "series": "DPC",
    "tagline": "Intel Core desktop PC with USB4 and triple-display connectivity",
    "description": "MCN7A offers Intel Core i3-1215U, i5-1235U or i7-12650H processor options, HDMI, DisplayPort and USB4, one 2.5GbE network port, dual NVMe slots and SATA storage. The compact enclosure measures 136 x 123 x 51 mm.",
    "highlights": [
      "Intel Core options",
      "USB4 + HDMI + DP",
      "1 x 2.5GbE",
      "Dual NVMe + SATA"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCN7A"
      },
      {
        "label": "CPU",
        "value": "Intel Core i3-1215U / i5-1235U / i7-12650H"
      },
      {
        "label": "Chipset",
        "value": "Intel Alder Lake/ Raptor Lake_U/P/H"
      },
      {
        "label": "Graphics",
        "value": "Intel Iris Xe Graphics"
      },
      {
        "label": "Display",
        "value": "HDMI+DP+Type-C (USB4) 4K@60Hz"
      },
      {
        "label": "Memory",
        "value": "2 x SO-DIMM DDR5 4800MHz Max 64G"
      },
      {
        "label": "Material",
        "value": "plastic plus metal"
      },
      {
        "label": "USB",
        "value": "2 x USB 2.0; 2 x USB 3.0; 1 x USB4"
      },
      {
        "label": "Power",
        "value": "DC19V 5.26~6.32A"
      },
      {
        "label": "Network",
        "value": "1 x RJ45 Intel 2.5G LAN"
      },
      {
        "label": "Storage",
        "value": "2 x M.2 (1 x PCIE4.0 x 4; 1 x PCIE3.0 x 4) NVME 2280 SSD; 1 x SATA3.0 slot for SATA HDD or SSD"
      },
      {
        "label": "Expansion",
        "value": "1 x SATA3.0 slot for SATA HDD or SSD; Wi-Fi5+BT4.2/Wi-Fi6+BT5.2"
      },
      {
        "label": "Dimensions",
        "value": "136mm x 123mm x 51mm"
      },
      {
        "label": "BIOS",
        "value": "AMI EFI BIOS"
      },
      {
        "label": "TDP",
        "value": "Depends on CPU"
      },
      {
        "label": "OS",
        "value": "Win11 64 Bit Ubuntu CentOS"
      },
      {
        "label": "Environment - Operating",
        "value": "0~60 C; 10%~90% Relative humidity; (no condensation)"
      },
      {
        "label": "Front I/O - Ports",
        "value": "1 x 3.5 mm audio jack; 2 x USB 3.2; 1 x Type-C (data)"
      },
      {
        "label": "Rear I/O - Ports",
        "value": "2 x USB 2.0; 1 x HDMI; 1 x DP; 1 x USB4; 1 x RJ45; 1 x DC IN"
      },
      {
        "label": "Internal I/O - Headers",
        "value": "1 x system cooling fan; 1 x half-size Mini PCIe slot for Wi-Fi/Bluetooth; 2 x M.2 slots for NVMe 2280 SSD; 1 x SATA 3.0 slot for HDD/SSD"
      }
    ],
    "image": "/assets/products/commercial/ver2/mcn7a/main.webp",
    "galleryImages": [
      "/assets/products/commercial/ver2/mcn7a/view-1.webp",
      "/assets/products/commercial/ver2/mcn7a/view-2.webp",
      "/assets/products/commercial/ver2/mcn7a/view-3.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/commercial/ver2/mcn7a/view-1.webp",
        "title": "MCN7A front panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mcn7a/view-2.webp",
        "title": "MCN7A rear panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mcn7a/view-3.webp",
        "title": "MCN7A enclosure view"
      }
    ],
    "sourceBrochure": "桌面端DPC/MCN7A Brochure.pdf",
    "sourceSha256": "0f518bb00546f1ca6ba1c71d30cfc1ee36471b83a01292bb2d4f3f1ea3d4e6a6",
    "operatingRange": "0°C to 60°C"
  },
  {
    "id": "mcn7p",
    "name": "MCN7P",
    "series": "DPC",
    "tagline": "AMD Ryzen HS desktop PC with USB4 and dual 2.5GbE",
    "description": "MCN7P combines AMD Ryzen 7 7735HS, Ryzen 7 7840HS or Ryzen 9 7940HS processor options, up to 64GB DDR5, dual 2.5GbE, USB4, dual PCIe 4.0 NVMe slots and SATA storage in a 136 x 123 x 51 mm enclosure.",
    "highlights": [
      "AMD Ryzen HS",
      "Up to 64GB DDR5",
      "Dual 2.5GbE",
      "Dual PCIe 4.0 NVMe"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCN7P"
      },
      {
        "label": "CPU",
        "value": "AMD Ryzen 7 7735HS / Ryzen 7 7840HS / Ryzen 9 7940HS"
      },
      {
        "label": "Chipset",
        "value": "AMD Rembrandt R/Phoenix U/H/HS series"
      },
      {
        "label": "Graphics",
        "value": "AMD Radeon 680M Graphics"
      },
      {
        "label": "Display",
        "value": "HDMI+DP+Type-C (USB4) 4K@60Hz"
      },
      {
        "label": "Memory",
        "value": "2 x SO-DIMM DDR5 4800/5600MHz Slot Support 16/ 32/ 64G"
      },
      {
        "label": "Material",
        "value": "plastic plus metal"
      },
      {
        "label": "USB",
        "value": "2 x USB 2.0; 2 x USB 3.0; 1 x USB4"
      },
      {
        "label": "Power",
        "value": "DC19V 5.26~6.32A"
      },
      {
        "label": "Network",
        "value": "2 x RJ45 Intel 2.5G LAN"
      },
      {
        "label": "Storage",
        "value": "2 x M.2 slot for PCIE4.0 x 4 NVME 2280 SSD; 1 x SATA3.0 slot for SATA HDD or SSD"
      },
      {
        "label": "Expansion",
        "value": "1 x SATA3.0 slot for SATA HDD or SSD; Wi-Fi5+BT4.2/Wi-Fi6+BT5.2"
      },
      {
        "label": "Dimensions",
        "value": "136mm x 123mm x 51mm"
      },
      {
        "label": "BIOS",
        "value": "AMI EFI BIOS"
      },
      {
        "label": "TDP",
        "value": "Depends on CPU"
      },
      {
        "label": "OS",
        "value": "Win11 64 Bit Ubuntu CentOS"
      },
      {
        "label": "Environment - Operating",
        "value": "0~60 C; 10%~90% Relative humidity; (no condensation)"
      },
      {
        "label": "Front I/O - Ports",
        "value": "1 x 3.5 mm audio jack; 2 x USB 3.2; 1 x Type-C (data)"
      },
      {
        "label": "Rear I/O - Ports",
        "value": "2 x USB 2.0; 1 x HDMI; 1 x DP; 1 x USB4; 2 x RJ45; 1 x DC IN"
      },
      {
        "label": "Internal I/O - Headers",
        "value": "1 x system cooling fan; 1 x half-size Mini PCIe slot for Wi-Fi/Bluetooth; 2 x M.2 slots for NVMe 2280 SSD; 1 x SATA 3.0 slot for HDD/SSD; 2 x DDR5 SO-DIMM slots"
      }
    ],
    "image": "/assets/products/commercial/ver2/mcn7p/main.webp",
    "galleryImages": [
      "/assets/products/commercial/ver2/mcn7p/view-1.webp",
      "/assets/products/commercial/ver2/mcn7p/view-2.webp",
      "/assets/products/commercial/ver2/mcn7p/view-3.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/commercial/ver2/mcn7p/view-1.webp",
        "title": "MCN7P front panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mcn7p/view-2.webp",
        "title": "MCN7P rear panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mcn7p/view-3.webp",
        "title": "MCN7P enclosure view"
      }
    ],
    "sourceBrochure": "桌面端DPC/MCN7P Brochure.pdf",
    "sourceSha256": "c74e198afe5e1b9495ff6f056ad6c257c5a04ff332565db0d7131fae14690fed",
    "operatingRange": "0°C to 60°C"
  },
  {
    "id": "mctar7",
    "name": "MCTAR7",
    "series": "DPC",
    "tagline": "Compact AMD Ryzen desktop PC with dual HDMI and full-featured Type-C",
    "description": "MCTAR7 offers configurable AMD Ryzen processors, Radeon graphics, DDR4 memory, dual HDMI and full-featured Type-C connectivity. NVMe and SATA M.2 storage, Gigabit Ethernet, Wi-Fi 6 and Bluetooth 5.2 support everyday desktop deployments.",
    "highlights": [
      "AMD Ryzen options",
      "Up to 32GB DDR4",
      "Dual HDMI + Type-C",
      "NVMe + SATA M.2"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTAR7"
      },
      {
        "label": "CPU",
        "value": "AMD Ryzen 7 4700U/5 5600U/7 5800U/R7-5825U; R5-7535U/R7-7730U Processor"
      },
      {
        "label": "Graphics",
        "value": "AMD Radeon Graphics"
      },
      {
        "label": "Display",
        "value": "2 x HDMI 1.4; 1 x Type-C (Full-featured)"
      },
      {
        "label": "Memory",
        "value": "2 x SO-DIMM DDR4 3200MHz Supports up to 32GB"
      },
      {
        "label": "USB",
        "value": "2 x USB3.1; 2 x USB3.0"
      },
      {
        "label": "Power",
        "value": "DC, 19V/3.42A Adapter"
      },
      {
        "label": "Network",
        "value": "1 x RJ45 1.0G Network interface"
      },
      {
        "label": "Storage",
        "value": "1 x M.2 PCIe 3.0 x 4 2280 SSD + 1 x M.2 NGFF SATA 2242 SSD; Supports up to 2TB"
      },
      {
        "label": "Wireless",
        "value": "WiFi-6, Bluetooth 5.2"
      },
      {
        "label": "Dimensions",
        "value": "105 x 115 x 35 mm"
      },
      {
        "label": "TDP",
        "value": "Depends on CPU"
      },
      {
        "label": "OS",
        "value": "Window 10/11 Home"
      },
      {
        "label": "Environment - Operating",
        "value": "0~50 C; 5%~90% Relative humidity; (no condensation)"
      },
      {
        "label": "Front I/O - Ports",
        "value": "1 x power button; 2 x USB 3.1"
      },
      {
        "label": "Rear I/O - Ports",
        "value": "1 x RJ45 1.0G Network interface; 1 x Type-C (Full-featured); 2 x HDMI 1.4; 1 x DC 19V; 1 x audio jack; 2 x USB3.0"
      }
    ],
    "image": "/assets/products/commercial/ver2/mctar7/main.webp",
    "galleryImages": [
      "/assets/products/commercial/ver2/mctar7/view-1.webp",
      "/assets/products/commercial/ver2/mctar7/view-2.webp",
      "/assets/products/commercial/ver2/mctar7/view-3.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/commercial/ver2/mctar7/view-1.webp",
        "title": "MCTAR7 front panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mctar7/view-2.webp",
        "title": "MCTAR7 rear panel"
      },
      {
        "image": "/assets/products/commercial/ver2/mctar7/view-3.webp",
        "title": "MCTAR7 enclosure view"
      }
    ],
    "sourceBrochure": "桌面端DPC/MCTAR7 brochure.pdf",
    "sourceSha256": "536d1f68159afd73ff7dd317e4884ee94fe5a30ea2f85732f480ddef463a1d29",
    "operatingRange": "0°C to 50°C"
  }
];
