// Reviewed TPC X brochures; generated by scripts/import-tpc-x-products.py.
export const tpcXProducts = [
  {
    "id": "mctpc-1004x",
    "name": "MCTPC-1004X",
    "series": "TPC",
    "tagline": "10.4-inch 1024 x 768 industrial panel PC with four platform options",
    "description": "MCTPC-1004X combines a 10.4-inch 1024 x 768 capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.",
    "highlights": [
      "10.4-inch capacitive display",
      "Four Intel platform options",
      "Dual Gigabit Ethernet",
      "IP65 front panel"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTPC-1004X"
      },
      {
        "label": "CPU",
        "value": "Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage"
      },
      {
        "label": "Display",
        "value": "10.4-inch TFT-LCD; 1024 x 768 (optional 800 x 600)"
      },
      {
        "label": "Touch",
        "value": "Projected capacitive touch; 85% transmittance"
      },
      {
        "label": "Color / brightness",
        "value": "50% sRGB; 300 cd/m² to 450 cd/m²"
      },
      {
        "label": "Viewing angle",
        "value": "70/70/60/70"
      },
      {
        "label": "Backlight life",
        "value": "30,000 hours"
      },
      {
        "label": "Display output",
        "value": "1 x HDMI"
      },
      {
        "label": "Graphics",
        "value": "Intel HD Graphics"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM, RS-232; COM1/COM2 support RS-485"
      },
      {
        "label": "Audio",
        "value": "3.5 mm audio; Realtek ALC897 codec"
      },
      {
        "label": "Power",
        "value": "DC 12 V standard, 5.5 x 2.5 mm; optional 9-36 V Phoenix terminal"
      },
      {
        "label": "Environment - Operating",
        "value": "-10 to 60 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Environment - Non-operating",
        "value": "-20 to 70 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Protection",
        "value": "IP65-rated front panel only"
      },
      {
        "label": "Dimensions",
        "value": "276.6 x 221.6 x 56.5 mm"
      },
      {
        "label": "Panel cutout",
        "value": "267 x 212 mm"
      },
      {
        "label": "Platform - J1900",
        "value": "Intel J1900; 1 x DDR3L SODIMM, max 8 GB; 1 x USB 3.0 + 3 x USB 2.0; 1 x mSATA (3 Gb/s)"
      },
      {
        "label": "Platform - Core 3rd Gen",
        "value": "Intel Core 3rd Gen; 1 x DDR3 SODIMM, max 8 GB; 4 x USB 3.0; 1 x mSATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 4th / 5th Gen",
        "value": "Intel Core 4th / 5th Gen; 2 x DDR3L SODIMM, max 16 GB; 4 x USB 3.0; 1 x mSATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 6th / 7th / 8th Gen",
        "value": "Intel Core 6th / 7th / 8th Gen; 2 x DDR4 SODIMM, max 32 GB; 4 x USB 3.0; 1 x mSATA (6 Gb/s)"
      },
      {
        "label": "Expansion - J1900",
        "value": "Mini PCIe full-size for Wi-Fi/4G; half-size for Wi-Fi; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 3rd Gen",
        "value": "Mini PCIe half-size for Wi-Fi only; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 4th / 5th Gen",
        "value": "Mini PCIe half-size for Wi-Fi/BT; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 6th / 7th / 8th Gen",
        "value": "Mini PCIe full-size for Wi-Fi/4G and half-size for Wi-Fi/BT; not two Wi-Fi modules at once; 1 x Nano SIM"
      },
      {
        "label": "GPIO",
        "value": "J1900 / Core 3rd / Core 4th-5th: 4-channel I/O GPIO; Core 6th-8th: 1 x 2-by-5-pin GPIO header"
      },
      {
        "label": "TPM 2.0",
        "value": "J1900 / Core 3rd / Core 4th-5th: reserved external header, module not fitted; Core 6th-8th: 1 x 2-by-7-pin header"
      },
      {
        "label": "OS",
        "value": "Core 3rd Gen: Windows XP / 7 / 10 / Linux; other platforms: Windows 7 / 10 / Linux"
      },
      {
        "label": "Configuration",
        "value": "Wi-Fi, Bluetooth, 4G and 9-36 V terminal are supported/options where stated; not standard installed parts."
      }
    ],
    "image": "/assets/products/industrial/ver2/mctpc-1004x/front.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mctpc-1004x/rear-core.webp",
      "/assets/products/industrial/ver2/mctpc-1004x/rear-j1900.webp",
      "/assets/products/industrial/ver2/mctpc-1004x/dimensions.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mctpc-1004x/rear-core.webp",
        "title": "MCTPC-1004X rear view — Core platforms"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1004x/rear-j1900.webp",
        "title": "MCTPC-1004X rear view — J1900"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1004x/dimensions.webp",
        "title": "MCTPC-1004X dimensions and panel cutout (mm)"
      }
    ],
    "operatingRange": "-10 to 60 °C / 5 to 95%RH, Non-condensing",
    "sourceBrochure": "工控机IPC/TPC系列/MCTPC-1004X brochure.pdf",
    "sourceSha256": "cca71518ed25fa2f1911a621ed0498bb99f3d6913150c5279665348baaff5c90"
  },
  {
    "id": "mctpc-1201x",
    "name": "MCTPC-1201X",
    "series": "TPC",
    "tagline": "12.1-inch 1024 x 768 industrial panel PC with four platform options",
    "description": "MCTPC-1201X combines a 12.1-inch 1024 x 768 capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.",
    "highlights": [
      "12.1-inch capacitive display",
      "Four Intel platform options",
      "Dual Gigabit Ethernet",
      "IP65 front panel"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTPC-1201X"
      },
      {
        "label": "CPU",
        "value": "Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage"
      },
      {
        "label": "Display",
        "value": "12.1-inch TFT-LCD; 1024 x 768"
      },
      {
        "label": "Touch",
        "value": "Projected capacitive touch; 85% transmittance"
      },
      {
        "label": "Color / brightness",
        "value": "72% sRGB; 500 cd/m²"
      },
      {
        "label": "Viewing angle",
        "value": "All-round perspective"
      },
      {
        "label": "Backlight life",
        "value": "50,000 hours"
      },
      {
        "label": "Display output",
        "value": "1 x HDMI"
      },
      {
        "label": "Graphics",
        "value": "Intel HD Graphics"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM, RS-232; COM1/COM2 support RS-485"
      },
      {
        "label": "Audio",
        "value": "3.5 mm audio; Realtek ALC897 codec"
      },
      {
        "label": "Power",
        "value": "DC 12 V standard, 5.5 x 2.5 mm; optional 9-36 V Phoenix terminal"
      },
      {
        "label": "Environment - Operating",
        "value": "-10 to 60 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Environment - Non-operating",
        "value": "-20 to 70 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Protection",
        "value": "IP65-rated front panel only"
      },
      {
        "label": "Dimensions",
        "value": "310.5 x 248.6 x 58.5 mm"
      },
      {
        "label": "Panel cutout",
        "value": "300 x 238 mm"
      },
      {
        "label": "Platform - J1900",
        "value": "Intel J1900; 1 x DDR3L SODIMM, max 8 GB; 1 x USB 3.0 + 3 x USB 2.0; 1 x mSATA (3 Gb/s)"
      },
      {
        "label": "Platform - Core 3rd Gen",
        "value": "Intel Core 3rd Gen; 1 x DDR3 SODIMM, max 8 GB; 4 x USB 3.0; 1 x mSATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 4th / 5th Gen",
        "value": "Intel Core 4th / 5th Gen; 2 x DDR3L SODIMM, max 16 GB; 4 x USB 3.0; 1 x mSATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 6th / 7th / 8th Gen",
        "value": "Intel Core 6th / 7th / 8th Gen; 2 x DDR4 SODIMM, max 32 GB; 4 x USB 3.0; 1 x mSATA (6 Gb/s)"
      },
      {
        "label": "Expansion - J1900",
        "value": "Mini PCIe full-size for Wi-Fi/4G; half-size for Wi-Fi; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 3rd Gen",
        "value": "Mini PCIe half-size for Wi-Fi only; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 4th / 5th Gen",
        "value": "Mini PCIe half-size for Wi-Fi/BT; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 6th / 7th / 8th Gen",
        "value": "Mini PCIe full-size for Wi-Fi/4G and half-size for Wi-Fi/BT; not two Wi-Fi modules at once; 1 x Nano SIM"
      },
      {
        "label": "GPIO",
        "value": "J1900 / Core 3rd / Core 4th-5th: 4-channel I/O GPIO; Core 6th-8th: 1 x 2-by-5-pin GPIO header"
      },
      {
        "label": "TPM 2.0",
        "value": "J1900 / Core 3rd / Core 4th-5th: reserved external header, module not fitted; Core 6th-8th: 1 x 2-by-7-pin header"
      },
      {
        "label": "OS",
        "value": "Core 3rd Gen: Windows XP / 7 / 10 / Linux; other platforms: Windows 7 / 10 / Linux"
      },
      {
        "label": "Configuration",
        "value": "Wi-Fi, Bluetooth, 4G and 9-36 V terminal are supported/options where stated; not standard installed parts."
      }
    ],
    "image": "/assets/products/industrial/ver2/mctpc-1201x/front.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mctpc-1201x/rear-core.webp",
      "/assets/products/industrial/ver2/mctpc-1201x/rear-j1900.webp",
      "/assets/products/industrial/ver2/mctpc-1201x/dimensions.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mctpc-1201x/rear-core.webp",
        "title": "MCTPC-1201X rear view — Core platforms"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1201x/rear-j1900.webp",
        "title": "MCTPC-1201X rear view — J1900"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1201x/dimensions.webp",
        "title": "MCTPC-1201X dimensions and panel cutout (mm)"
      }
    ],
    "operatingRange": "-10 to 60 °C / 5 to 95%RH, Non-condensing",
    "sourceBrochure": "工控机IPC/TPC系列/MCTPC-1201X brochure.pdf",
    "sourceSha256": "09e44d05e0b385f4e7ca4414f2d84d1c9ed7d3d3c06714908d6b7e0453881527"
  },
  {
    "id": "mctpc-1501x",
    "name": "MCTPC-1501X",
    "series": "TPC",
    "tagline": "15.0-inch 1024 x 768 industrial panel PC with four platform options",
    "description": "MCTPC-1501X combines a 15.0-inch 1024 x 768 capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.",
    "highlights": [
      "15.0-inch capacitive display",
      "Four Intel platform options",
      "Dual Gigabit Ethernet",
      "IP65 front panel"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTPC-1501X"
      },
      {
        "label": "CPU",
        "value": "Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage"
      },
      {
        "label": "Display",
        "value": "15.0-inch TFT-LCD; 1024 x 768"
      },
      {
        "label": "Touch",
        "value": "Projected capacitive touch; 85% transmittance"
      },
      {
        "label": "Color / brightness",
        "value": "72% sRGB; 350 cd/m²"
      },
      {
        "label": "Viewing angle",
        "value": "All-round perspective"
      },
      {
        "label": "Backlight life",
        "value": "50,000 hours"
      },
      {
        "label": "Display output",
        "value": "1 x HDMI"
      },
      {
        "label": "Graphics",
        "value": "Intel HD Graphics"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM, RS-232; COM1/COM2 support RS-485"
      },
      {
        "label": "Audio",
        "value": "3.5 mm audio; Realtek ALC897 codec"
      },
      {
        "label": "Power",
        "value": "DC 12 V standard, 5.5 x 2.5 mm; optional 9-36 V Phoenix terminal"
      },
      {
        "label": "Environment - Operating",
        "value": "-10 to 60 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Environment - Non-operating",
        "value": "-20 to 70 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Protection",
        "value": "IP65-rated front panel only"
      },
      {
        "label": "Dimensions",
        "value": "366 x 290 x 58 mm"
      },
      {
        "label": "Panel cutout",
        "value": "353 x 277 mm"
      },
      {
        "label": "Platform - J1900",
        "value": "Intel J1900; 1 x DDR3L SODIMM, max 8 GB; 1 x USB 3.0 + 5 x USB 2.0; 1 x mSATA (3 Gb/s); 1 x SATA (3 Gb/s)"
      },
      {
        "label": "Platform - Core 3rd Gen",
        "value": "Intel Core 3rd Gen; 1 x DDR3 SODIMM, max 8 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 4th / 5th Gen",
        "value": "Intel Core 4th / 5th Gen; 2 x DDR3L SODIMM, max 16 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 6th / 7th / 8th Gen",
        "value": "Intel Core 6th / 7th / 8th Gen; 2 x DDR4 SODIMM, max 32 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Expansion - J1900",
        "value": "Mini PCIe full-size for Wi-Fi/4G; half-size for Wi-Fi; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 3rd Gen",
        "value": "Mini PCIe half-size for Wi-Fi only; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 4th / 5th Gen",
        "value": "Mini PCIe half-size for Wi-Fi/BT; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 6th / 7th / 8th Gen",
        "value": "Mini PCIe full-size for Wi-Fi/4G and half-size for Wi-Fi/BT; not two Wi-Fi modules at once; 1 x Nano SIM"
      },
      {
        "label": "GPIO",
        "value": "J1900 / Core 3rd / Core 4th-5th: 4-channel I/O GPIO; Core 6th-8th: 1 x 2-by-5-pin GPIO header"
      },
      {
        "label": "TPM 2.0",
        "value": "J1900 / Core 3rd / Core 4th-5th: reserved external header, module not fitted; Core 6th-8th: 1 x 2-by-7-pin header"
      },
      {
        "label": "OS",
        "value": "Core 3rd Gen: Windows XP / 7 / 10 / Linux; other platforms: Windows 7 / 10 / Linux"
      },
      {
        "label": "Configuration",
        "value": "Wi-Fi, Bluetooth, 4G and 9-36 V terminal are supported/options where stated; not standard installed parts."
      }
    ],
    "image": "/assets/products/industrial/ver2/mctpc-1501x/front.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mctpc-1501x/rear-core.webp",
      "/assets/products/industrial/ver2/mctpc-1501x/rear-j1900.webp",
      "/assets/products/industrial/ver2/mctpc-1501x/dimensions.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mctpc-1501x/rear-core.webp",
        "title": "MCTPC-1501X rear view — Core platforms"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1501x/rear-j1900.webp",
        "title": "MCTPC-1501X rear view — J1900"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1501x/dimensions.webp",
        "title": "MCTPC-1501X dimensions and panel cutout (mm)"
      }
    ],
    "operatingRange": "-10 to 60 °C / 5 to 95%RH, Non-condensing",
    "sourceBrochure": "工控机IPC/TPC系列/MCTPC-1501X brochure.pdf",
    "sourceSha256": "03855bcefb40b84df6ca5b127804e5371e8a78936870a5a47084302a99d3b745"
  },
  {
    "id": "mctpc-1506x",
    "name": "MCTPC-1506X",
    "series": "TPC",
    "tagline": "15.6-inch 1920 x 1080 industrial panel PC with four platform options",
    "description": "MCTPC-1506X combines a 15.6-inch 1920 x 1080 capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.",
    "highlights": [
      "15.6-inch capacitive display",
      "Four Intel platform options",
      "Dual Gigabit Ethernet",
      "IP65 front panel"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTPC-1506X"
      },
      {
        "label": "CPU",
        "value": "Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage"
      },
      {
        "label": "Display",
        "value": "15.6-inch TFT-LCD; 1920 x 1080"
      },
      {
        "label": "Touch",
        "value": "Projected capacitive touch; 85% transmittance"
      },
      {
        "label": "Color / brightness",
        "value": "45% sRGB; 250 cd/m²"
      },
      {
        "label": "Viewing angle",
        "value": "85/85/85/85"
      },
      {
        "label": "Backlight life",
        "value": "15,000 hours"
      },
      {
        "label": "Display output",
        "value": "1 x HDMI"
      },
      {
        "label": "Graphics",
        "value": "Intel HD Graphics"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM, RS-232; COM1/COM2 support RS-485"
      },
      {
        "label": "Audio",
        "value": "3.5 mm audio; Realtek ALC897 codec"
      },
      {
        "label": "Power",
        "value": "DC 12 V standard, 5.5 x 2.5 mm; optional 9-36 V Phoenix terminal"
      },
      {
        "label": "Environment - Operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Environment - Non-operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Protection",
        "value": "IP65-rated front panel only"
      },
      {
        "label": "Dimensions",
        "value": "411.6 x 255.6 x 52.5 mm"
      },
      {
        "label": "Panel cutout",
        "value": "400 x 244 mm"
      },
      {
        "label": "Platform - J1900",
        "value": "Intel J1900; 1 x DDR3L SODIMM, max 8 GB; 1 x USB 3.0 + 5 x USB 2.0; 1 x mSATA (3 Gb/s); 1 x SATA (3 Gb/s)"
      },
      {
        "label": "Platform - Core 3rd Gen",
        "value": "Intel Core 3rd Gen; 1 x DDR3 SODIMM, max 8 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 4th / 5th Gen",
        "value": "Intel Core 4th / 5th Gen; 2 x DDR3L SODIMM, max 16 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 6th / 7th / 8th Gen",
        "value": "Intel Core 6th / 7th / 8th Gen; 2 x DDR4 SODIMM, max 32 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Expansion - J1900",
        "value": "Mini PCIe full-size for Wi-Fi/4G; half-size for Wi-Fi; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 3rd Gen",
        "value": "Mini PCIe half-size for Wi-Fi only; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 4th / 5th Gen",
        "value": "Mini PCIe half-size for Wi-Fi/BT; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 6th / 7th / 8th Gen",
        "value": "Mini PCIe full-size for Wi-Fi/4G and half-size for Wi-Fi/BT; not two Wi-Fi modules at once; 1 x Nano SIM"
      },
      {
        "label": "GPIO",
        "value": "J1900 / Core 3rd / Core 4th-5th: 4-channel I/O GPIO; Core 6th-8th: 1 x 2-by-5-pin GPIO header"
      },
      {
        "label": "TPM 2.0",
        "value": "J1900 / Core 3rd / Core 4th-5th: reserved external header, module not fitted; Core 6th-8th: 1 x 2-by-7-pin header"
      },
      {
        "label": "OS",
        "value": "Core 3rd Gen: Windows XP / 7 / 10 / Linux; other platforms: Windows 7 / 10 / Linux"
      },
      {
        "label": "Configuration",
        "value": "Wi-Fi, Bluetooth, 4G and 9-36 V terminal are supported/options where stated; not standard installed parts."
      }
    ],
    "image": "/assets/products/industrial/ver2/mctpc-1506x/front.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mctpc-1506x/rear-core.webp",
      "/assets/products/industrial/ver2/mctpc-1506x/rear-j1900.webp",
      "/assets/products/industrial/ver2/mctpc-1506x/dimensions.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mctpc-1506x/rear-core.webp",
        "title": "MCTPC-1506X rear view — Core platforms"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1506x/rear-j1900.webp",
        "title": "MCTPC-1506X rear view — J1900"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1506x/dimensions.webp",
        "title": "MCTPC-1506X dimensions and panel cutout (mm)"
      }
    ],
    "operatingRange": "0 to 50 °C / 5 to 95%RH, Non-condensing",
    "sourceBrochure": "工控机IPC/TPC系列/MCTPC-1506X brochure.pdf",
    "sourceSha256": "e6a272f7729be1051d15cea031921912245daa6f0f6a94dc5753b04d4dbb5a40"
  },
  {
    "id": "mctpc-1701x",
    "name": "MCTPC-1701X",
    "series": "TPC",
    "tagline": "17.0-inch 1280 x 1024 industrial panel PC with four platform options",
    "description": "MCTPC-1701X combines a 17.0-inch 1280 x 1024 capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.",
    "highlights": [
      "17.0-inch capacitive display",
      "Four Intel platform options",
      "Dual Gigabit Ethernet",
      "IP65 front panel"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTPC-1701X"
      },
      {
        "label": "CPU",
        "value": "Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage"
      },
      {
        "label": "Display",
        "value": "17.0-inch TFT-LCD; 1280 x 1024"
      },
      {
        "label": "Touch",
        "value": "Projected capacitive touch; 85% transmittance"
      },
      {
        "label": "Color / brightness",
        "value": "72% sRGB; 250 cd/m²"
      },
      {
        "label": "Viewing angle",
        "value": "85/85/85/85"
      },
      {
        "label": "Backlight life",
        "value": "30,000 hours"
      },
      {
        "label": "Display output",
        "value": "1 x HDMI"
      },
      {
        "label": "Graphics",
        "value": "Intel HD Graphics"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM, RS-232; COM1/COM2 support RS-485"
      },
      {
        "label": "Audio",
        "value": "3.5 mm audio; Realtek ALC897 codec"
      },
      {
        "label": "Power",
        "value": "DC 12 V standard, 5.5 x 2.5 mm; optional 9-36 V Phoenix terminal"
      },
      {
        "label": "Environment - Operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Environment - Non-operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Protection",
        "value": "IP65-rated front panel only"
      },
      {
        "label": "Dimensions",
        "value": "402.5 x 335 x 59.5 mm"
      },
      {
        "label": "Panel cutout",
        "value": "389 x 321 mm"
      },
      {
        "label": "Platform - J1900",
        "value": "Intel J1900; 1 x DDR3L SODIMM, max 8 GB; 1 x USB 3.0 + 5 x USB 2.0; 1 x mSATA (3 Gb/s); 1 x SATA (3 Gb/s)"
      },
      {
        "label": "Platform - Core 3rd Gen",
        "value": "Intel Core 3rd Gen; 1 x DDR3 SODIMM, max 8 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 4th / 5th Gen",
        "value": "Intel Core 4th / 5th Gen; 2 x DDR3L SODIMM, max 16 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 6th / 7th / 8th Gen",
        "value": "Intel Core 6th / 7th / 8th Gen; 2 x DDR4 SODIMM, max 32 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Expansion - J1900",
        "value": "Mini PCIe full-size for Wi-Fi/4G; half-size for Wi-Fi; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 3rd Gen",
        "value": "Mini PCIe half-size for Wi-Fi only; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 4th / 5th Gen",
        "value": "Mini PCIe half-size for Wi-Fi/BT; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 6th / 7th / 8th Gen",
        "value": "Mini PCIe full-size for Wi-Fi/4G and half-size for Wi-Fi/BT; not two Wi-Fi modules at once; 1 x Nano SIM"
      },
      {
        "label": "GPIO",
        "value": "J1900 / Core 3rd / Core 4th-5th: 4-channel I/O GPIO; Core 6th-8th: 1 x 2-by-5-pin GPIO header"
      },
      {
        "label": "TPM 2.0",
        "value": "J1900 / Core 3rd / Core 4th-5th: reserved external header, module not fitted; Core 6th-8th: 1 x 2-by-7-pin header"
      },
      {
        "label": "OS",
        "value": "Core 3rd Gen: Windows XP / 7 / 10 / Linux; other platforms: Windows 7 / 10 / Linux"
      },
      {
        "label": "Configuration",
        "value": "Wi-Fi, Bluetooth, 4G and 9-36 V terminal are supported/options where stated; not standard installed parts."
      }
    ],
    "image": "/assets/products/industrial/ver2/mctpc-1701x/front.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mctpc-1701x/rear-core.webp",
      "/assets/products/industrial/ver2/mctpc-1701x/rear-j1900.webp",
      "/assets/products/industrial/ver2/mctpc-1701x/dimensions.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mctpc-1701x/rear-core.webp",
        "title": "MCTPC-1701X rear view — Core platforms"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1701x/rear-j1900.webp",
        "title": "MCTPC-1701X rear view — J1900"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1701x/dimensions.webp",
        "title": "MCTPC-1701X dimensions and panel cutout (mm)"
      }
    ],
    "operatingRange": "0 to 50 °C / 5 to 95%RH, Non-condensing",
    "sourceBrochure": "工控机IPC/TPC系列/MCTPC-1701X brochure.pdf",
    "sourceSha256": "72761fde56fafa176ec888e3559900ade0e9f52769b509c2dd7b9d4ff2ee748d"
  },
  {
    "id": "mctpc-1901x",
    "name": "MCTPC-1901X",
    "series": "TPC",
    "tagline": "19.0-inch 1280 x 1024 industrial panel PC with four platform options",
    "description": "MCTPC-1901X combines a 19.0-inch 1280 x 1024 capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.",
    "highlights": [
      "19.0-inch capacitive display",
      "Four Intel platform options",
      "Dual Gigabit Ethernet",
      "IP65 front panel"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTPC-1901X"
      },
      {
        "label": "CPU",
        "value": "Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage"
      },
      {
        "label": "Display",
        "value": "19.0-inch TFT-LCD; 1280 x 1024"
      },
      {
        "label": "Touch",
        "value": "Projected capacitive touch; 85% transmittance"
      },
      {
        "label": "Color / brightness",
        "value": "72% sRGB; 250 cd/m²"
      },
      {
        "label": "Viewing angle",
        "value": "All-round perspective"
      },
      {
        "label": "Backlight life",
        "value": "30,000 hours"
      },
      {
        "label": "Display output",
        "value": "1 x HDMI"
      },
      {
        "label": "Graphics",
        "value": "Intel HD Graphics"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM, RS-232; COM1/COM2 support RS-485"
      },
      {
        "label": "Audio",
        "value": "3.5 mm audio; Realtek ALC897 codec"
      },
      {
        "label": "Power",
        "value": "DC 12 V standard, 5.5 x 2.5 mm; optional 9-36 V Phoenix terminal"
      },
      {
        "label": "Environment - Operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Environment - Non-operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Protection",
        "value": "IP65-rated front panel only"
      },
      {
        "label": "Dimensions",
        "value": "443.6 x 367.6 x 60.5 mm"
      },
      {
        "label": "Panel cutout",
        "value": "426 x 350 mm"
      },
      {
        "label": "Platform - J1900",
        "value": "Intel J1900; 1 x DDR3L SODIMM, max 8 GB; 1 x USB 3.0 + 5 x USB 2.0; 1 x mSATA (3 Gb/s); 1 x SATA (3 Gb/s)"
      },
      {
        "label": "Platform - Core 3rd Gen",
        "value": "Intel Core 3rd Gen; 1 x DDR3 SODIMM, max 8 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 4th / 5th Gen",
        "value": "Intel Core 4th / 5th Gen; 2 x DDR3L SODIMM, max 16 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 6th / 7th / 8th Gen",
        "value": "Intel Core 6th / 7th / 8th Gen; 2 x DDR4 SODIMM, max 32 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Expansion - J1900",
        "value": "Mini PCIe full-size for Wi-Fi/4G; half-size for Wi-Fi; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 3rd Gen",
        "value": "Mini PCIe half-size for Wi-Fi only; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 4th / 5th Gen",
        "value": "Mini PCIe half-size for Wi-Fi/BT; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 6th / 7th / 8th Gen",
        "value": "Mini PCIe full-size for Wi-Fi/4G and half-size for Wi-Fi/BT; not two Wi-Fi modules at once; 1 x Nano SIM"
      },
      {
        "label": "GPIO",
        "value": "J1900 / Core 3rd / Core 4th-5th: 4-channel I/O GPIO; Core 6th-8th: 1 x 2-by-5-pin GPIO header"
      },
      {
        "label": "TPM 2.0",
        "value": "J1900 / Core 3rd / Core 4th-5th: reserved external header, module not fitted; Core 6th-8th: 1 x 2-by-7-pin header"
      },
      {
        "label": "OS",
        "value": "Core 3rd Gen: Windows XP / 7 / 10 / Linux; other platforms: Windows 7 / 10 / Linux"
      },
      {
        "label": "Configuration",
        "value": "Wi-Fi, Bluetooth, 4G and 9-36 V terminal are supported/options where stated; not standard installed parts."
      }
    ],
    "image": "/assets/products/industrial/ver2/mctpc-1901x/front.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mctpc-1901x/rear-core.webp",
      "/assets/products/industrial/ver2/mctpc-1901x/rear-j1900.webp",
      "/assets/products/industrial/ver2/mctpc-1901x/dimensions.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mctpc-1901x/rear-core.webp",
        "title": "MCTPC-1901X rear view — Core platforms"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1901x/rear-j1900.webp",
        "title": "MCTPC-1901X rear view — J1900"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-1901x/dimensions.webp",
        "title": "MCTPC-1901X dimensions and panel cutout (mm)"
      }
    ],
    "operatingRange": "0 to 50 °C / 5 to 95%RH, Non-condensing",
    "sourceBrochure": "工控机IPC/TPC系列/MCTPC-1901X brochure.pdf",
    "sourceSha256": "1e7a21891debfd28992c88361ba4e6fcf0514ece6a967535f13de8685831ac88"
  },
  {
    "id": "mctpc-2105x",
    "name": "MCTPC-2105X",
    "series": "TPC",
    "tagline": "21.5-inch 1920 x 1080 industrial panel PC with four platform options",
    "description": "MCTPC-2105X combines a 21.5-inch 1920 x 1080 capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.",
    "highlights": [
      "21.5-inch capacitive display",
      "Four Intel platform options",
      "Dual Gigabit Ethernet",
      "IP65 front panel"
    ],
    "specs": [
      {
        "label": "Model",
        "value": "MCTPC-2105X"
      },
      {
        "label": "CPU",
        "value": "Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage"
      },
      {
        "label": "Display",
        "value": "21.5-inch TFT-LCD; 1920 x 1080"
      },
      {
        "label": "Touch",
        "value": "Projected capacitive touch; 85% transmittance"
      },
      {
        "label": "Color / brightness",
        "value": "72% sRGB; 250 cd/m²"
      },
      {
        "label": "Viewing angle",
        "value": "All-round perspective"
      },
      {
        "label": "Backlight life",
        "value": "30,000 hours"
      },
      {
        "label": "Display output",
        "value": "1 x HDMI"
      },
      {
        "label": "Graphics",
        "value": "Intel HD Graphics"
      },
      {
        "label": "Network",
        "value": "2 x Realtek RTL8111H Gigabit Ethernet ports"
      },
      {
        "label": "Serial",
        "value": "2 x DB9 COM, RS-232; COM1/COM2 support RS-485"
      },
      {
        "label": "Audio",
        "value": "3.5 mm audio; Realtek ALC897 codec"
      },
      {
        "label": "Power",
        "value": "DC 12 V standard, 5.5 x 2.5 mm; optional 9-36 V Phoenix terminal"
      },
      {
        "label": "Environment - Operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Environment - Non-operating",
        "value": "0 to 50 °C / 5 to 95%RH, Non-condensing"
      },
      {
        "label": "Protection",
        "value": "IP65-rated front panel only"
      },
      {
        "label": "Dimensions",
        "value": "538.2 x 334.2 x 62 mm"
      },
      {
        "label": "Panel cutout",
        "value": "525 x 321 mm"
      },
      {
        "label": "Platform - J1900",
        "value": "Intel J1900; 1 x DDR3L SODIMM, max 8 GB; 1 x USB 3.0 + 5 x USB 2.0; 1 x mSATA (3 Gb/s); 1 x SATA (3 Gb/s)"
      },
      {
        "label": "Platform - Core 3rd Gen",
        "value": "Intel Core 3rd Gen; 1 x DDR3 SODIMM, max 8 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 4th / 5th Gen",
        "value": "Intel Core 4th / 5th Gen; 2 x DDR3L SODIMM, max 16 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Platform - Core 6th / 7th / 8th Gen",
        "value": "Intel Core 6th / 7th / 8th Gen; 2 x DDR4 SODIMM, max 32 GB; 4 x USB 3.0 + 2 x USB 2.0; 1 x mSATA (6 Gb/s); 1 x SATA (6 Gb/s)"
      },
      {
        "label": "Expansion - J1900",
        "value": "Mini PCIe full-size for Wi-Fi/4G; half-size for Wi-Fi; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 3rd Gen",
        "value": "Mini PCIe half-size for Wi-Fi only; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 4th / 5th Gen",
        "value": "Mini PCIe half-size for Wi-Fi/BT; full-size for Wi-Fi/4G; 1 x Nano SIM"
      },
      {
        "label": "Expansion - Core 6th / 7th / 8th Gen",
        "value": "Mini PCIe full-size for Wi-Fi/4G and half-size for Wi-Fi/BT; not two Wi-Fi modules at once; 1 x Nano SIM"
      },
      {
        "label": "GPIO",
        "value": "J1900 / Core 3rd / Core 4th-5th: 4-channel I/O GPIO; Core 6th-8th: 1 x 2-by-5-pin GPIO header"
      },
      {
        "label": "TPM 2.0",
        "value": "J1900 / Core 3rd / Core 4th-5th: reserved external header, module not fitted; Core 6th-8th: 1 x 2-by-7-pin header"
      },
      {
        "label": "OS",
        "value": "Core 3rd Gen: Windows XP / 7 / 10 / Linux; other platforms: Windows 7 / 10 / Linux"
      },
      {
        "label": "Configuration",
        "value": "Wi-Fi, Bluetooth, 4G and 9-36 V terminal are supported/options where stated; not standard installed parts."
      }
    ],
    "image": "/assets/products/industrial/ver2/mctpc-2105x/front.webp",
    "galleryImages": [
      "/assets/products/industrial/ver2/mctpc-2105x/rear-core.webp",
      "/assets/products/industrial/ver2/mctpc-2105x/rear-j1900.webp",
      "/assets/products/industrial/ver2/mctpc-2105x/dimensions.webp"
    ],
    "galleryCards": [
      {
        "image": "/assets/products/industrial/ver2/mctpc-2105x/rear-core.webp",
        "title": "MCTPC-2105X rear view — Core platforms"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-2105x/rear-j1900.webp",
        "title": "MCTPC-2105X rear view — J1900"
      },
      {
        "image": "/assets/products/industrial/ver2/mctpc-2105x/dimensions.webp",
        "title": "MCTPC-2105X dimensions and panel cutout (mm)"
      }
    ],
    "operatingRange": "0 to 50 °C / 5 to 95%RH, Non-condensing",
    "sourceBrochure": "工控机IPC/TPC系列/MCTPC-2105X brochure.pdf",
    "sourceSha256": "140fd43161a2d3a70a17352083640580d2f7868af63196f07f0fc021297f0294"
  }
];
