"""Import reviewed two-page TPC X brochures. External sources remain read-only."""
import hashlib
import importlib.util
import json
from pathlib import Path

import pdfplumber
from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('brochures', ROOT / 'scripts/import-september-products.py')
brochures = importlib.util.module_from_spec(spec)
spec.loader.exec_module(brochures)
spec = importlib.util.spec_from_file_location('views', ROOT / 'scripts/pdf-product-images.py')
views = importlib.util.module_from_spec(spec)
spec.loader.exec_module(views)


def build():
    records = []
    for code in ['1004', '1201', '1501', '1506', '1701', '1901', '2105']:
        name = f'MCTPC-{code}X'
        source = brochures.source_file(name)
        with pdfplumber.open(source) as pdf:
            assert len(pdf.pages) == 2
            common = brochures.specifications(pdf.pages[0], name)
            options = brochures.specifications(pdf.pages[1], name)[1:]
        assert len(common) == 17 and len(options) == 12
        assert '(cid:' not in json.dumps(common + options)
        for row in common:
            row['label'] = {'Panel': 'Display', 'Display': 'Display output', 'DC input': 'Power', 'Front panel': 'Protection'}.get(row['label'], row['label'])
            row['value'] = row['value'].replace(' C/', ' °C / ')
        for i, row in enumerate(options[:8]):
            row['label'] = ('Platform - ' if i < 4 else 'Expansion - ') + row['label']
        cpu = {'label': 'CPU', 'value': 'Intel J1900 or Intel Core 3rd / 4th / 5th / 6th / 7th / 8th Gen; configuration-dependent memory, USB and storage'}
        rows = common[:1] + [cpu] + common[1:] + options
        panel = next(r['value'] for r in rows if r['label'] == 'Display')
        size = panel.split('-inch')[0]
        resolution = panel.split('; ')[1].split(' (')[0]
        reader = PdfReader(source)
        front, core = views.rendered_images(reader.pages[0])
        j1900, drawing = views.rendered_images(reader.pages[1])
        base = f'/assets/products/industrial/ver2/{name.lower()}'
        gallery = []
        for filename, im, title in [('front', front, 'front view'), ('rear-core', core, 'rear view — Core platforms'), ('rear-j1900', j1900, 'rear view — J1900'), ('dimensions', drawing, 'dimensions and panel cutout (mm)')]:
            brochures.square(im, ROOT / 'public' / base.lstrip('/') / f'{filename}.webp')
            if filename != 'front':
                gallery.append({'image': f'{base}/{filename}.webp', 'title': f'{name} {title}'})
        description = f'{name} combines a {size}-inch {resolution} capacitive display with Intel J1900 or Core 3rd–8th Gen platform options. Dual Gigabit Ethernet and two RS-232/RS-485 COM ports support equipment integration. The front panel is IP65-rated; standard power is 12V DC, with an optional 9–36V Phoenix terminal. Memory, USB and storage specifications are listed separately for each platform.'
        record = dict(id=name.lower(), name=name, series='TPC', tagline=f'{size}-inch {resolution} industrial panel PC with four platform options', description=description,
                      highlights=[f'{size}-inch capacitive display', 'Four Intel platform options', 'Dual Gigabit Ethernet', 'IP65 front panel'], specs=rows,
                      image=f'{base}/front.webp', galleryImages=[g['image'] for g in gallery], galleryCards=gallery,
                      operatingRange=next(r['value'] for r in rows if r['label'] == 'Environment - Operating'),
                      sourceBrochure=source.relative_to(brochures.SOURCE_ROOT).as_posix(), sourceSha256=hashlib.sha256(source.read_bytes()).hexdigest())
        records.append(record)
        cms = {k: v for k, v in record.items() if k not in ['series', 'specs', 'image']}
        cms.update(category='industrial-mini-pc', images=[record['image']], specifications=rows)
        (ROOT / f'content/products/items/{record["id"]}.json').write_text(json.dumps(cms, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    (ROOT / 'lib/tpc-x-products.ts').write_text('// Reviewed TPC X brochures; generated by scripts/import-tpc-x-products.py.\nexport const tpcXProducts = '+json.dumps(records, ensure_ascii=False, indent=2)+';\n', encoding='utf-8')
    print('Imported', len(records), 'TPC X products')


if __name__ == '__main__':
    build()
